# ==========================================================
# 🚀 Build and Deploy Angular Frontend to Azure Static Web App (DEV)
# Ambiente: Desenvolvimento
# Serviço destino: web-versopay-dev (Azure Static Web App)
# ==========================================================

name: Build and deploy Angular app to Azure Static Web App - web-versopay-dev

on:
  push:
    branches:
      - main # ou 'develop' se preferir deploy do ambiente de dev nessa branch
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular Frontend

    steps:
      # -------------------------------
      # 1️⃣ Clonar repositório
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 2️⃣ Configurar Node.js (v18 LTS recomendado)
      # -------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      # -------------------------------
      # 3️⃣ Instalar dependências
      # -------------------------------
      - name: Install dependencies
        run: npm ci

      # -------------------------------
      # 4️⃣ Buildar o projeto Angular
      # -------------------------------
      - name: Build Angular app
        run: npm run build --if-present

      # -------------------------------
      # 5️⃣ Deploy no Azure Static Web App
      # -------------------------------
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WEB_VERSOPAY_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Necessário para pull requests
          action: "upload"
          ###### Caminhos de build ######
          app_location: "/"                    # Raiz do projeto Angular
          api_location: ""                     # Sem backend aqui
          output_location: "dist/VersopayFrontend" # Pasta gerada pelo ng build
          ###### Opções adicionais ######
          skip_app_build: false
          production_branch: main
