# ==========================================================
# 🚀 Azure Static Web Apps CI/CD - Versopay Frontend (DEV)
# Ambiente: Desenvolvimento
# Serviço destino: web-versopay-dev (Azure Static Web App)
# ==========================================================

name: Azure Static Web Apps CI/CD - web-versopay-dev

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Angular Frontend

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WEB_VERSOPAY_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para PR comments e integração GitHub
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # Caminho do projeto Angular
          api_location: ""  # Não há API nesse repositório
          output_location: "dist/versopay-web" # Caminho gerado pelo ng build
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WEB_VERSOPAY_DEV }}
          action: "close"

